[defaults."*.md"]
# allow multiple content passes (e.g. expand templates, markdown to html)?
process_content = "markdown_to_html"

[defaults."blog/*"]
path = "blog/{date.year}/{date.month}/{date.day}/{slug}/"
template = "blog_article.html"
